/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/occurrences": {
    /**
     * Get Occurrences
     * @description Gets all occurrences in a single dataset where the price change between start_date and end_date is equal to or greater than the specified percentage.
     *
     * Args:
     *     key (str): The dataset key, e.g (ETHUSDT).
     *     percentage_change (float): The percentage change to look for.
     *     start_date (str): The start date of the date range in 'YYYY-MM-DD' format.
     *     end_date (str): The end date of the date range in 'YYYY-MM-DD' format.
     *
     * Returns:
     *     List[CryptoData]: A list of occurrences that match the criteria.
     */
    get: operations["get_occurrences_occurrences_get"];
  };
  "/occurrences_keys": {
    /**
     * Get Occurrences For Keys
     * @description Gets all occurrences where the price change between start_date and end_date is equal to or greater than the specified percentage
     * within the given date range for multiple datasets.
     *
     * Args:
     *     keys (List[str]): The S3 keys for the Parquet files.
     *     percentage_change (float): The percentage change to look for.
     *     start_date (str): The start date of the date range in 'YYYY-MM-DD' format.
     *     end_date (str): The end date of the date range in 'YYYY-MM-DD' format.
     *
     * Returns:
     *     List[CryptoData]: A list of occurrences that match the criteria.
     */
    get: operations["get_occurrences_for_keys_occurrences_keys_get"];
  };
  "/occurrences_keys_for_n_days": {
    /**
     * Get Occurrences For Keys For N Days
     * @description Gets all occurrences where the price change between start_date and end_date is equal to or greater than the specified percentage
     * within the given date range for multiple datasets.
     *
     * Args:
     *     keys (List[str]): The S3 keys for the Parquet files.
     *     percentage_change (float): The percentage change to look for.
     *     start_date (str): The start date of the date range in 'YYYY-MM-DD' format.
     *     end_date (str): The end date of the date range in 'YYYY-MM-DD' format.
     *     day_shift (str): The number of days over which to consider the price_change.
     *
     * Returns:
     *     List[CryptoData]: A list of occurrences that match the criteria.
     */
    get: operations["get_occurrences_for_keys_for_n_days_occurrences_keys_for_n_days_get"];
  };
  "/all_occurrences": {
    /**
     * Get Occurrences All
     * @description Gets all occurrences where the price drop between start_date and end_date is equal to or greater than the specified percentage
     * across all datasets.
     *
     * Args:
     *     percentage_change (float): The percentage drop to look for.
     *     start_date (str): The start date of the date range in 'YYYY-MM-DD' format.
     *     end_date (str): The end date of the date range in 'YYYY-MM-DD' format.
     *
     * Returns:
     *     List[CryptoData]: A list of occurrences that match the criteria.
     */
    get: operations["get_occurrences_all_all_occurrences_get"];
  };
  "/datasets": {
    /**
     * List Datasets
     * @description Lists all available datasets in the S3 bucket.
     *
     * Returns:
     *     List[str]: A list of available dataset keys.
     */
    get: operations["list_datasets_datasets_get"];
  };
  "/dataset_dates/{key}": {
    /**
     * List Dataset Dates
     * @description Lists all available dates for a given dataset.
     *
     * Args:
     *     key (str): The S3 key for the dataset.
     *
     * Returns:
     *     List[str]: A list of available dates for the given dataset.
     */
    get: operations["list_dataset_dates_dataset_dates__key__get"];
  };
  "/candlestick_data": {
    /**
     * Get Candlestick Data
     * @description Gets the candlestick data for a given dataset within a specified date range.
     *
     * Args:
     *     key (str): The dataset key, e.g (ETHUSDT).
     *     start_date (str): The start date of the date range in 'YYYY-MM-DD' format.
     *     end_date (str): The end date of the date range in 'YYYY-MM-DD' format.
     *
     * Returns:
     *     List[CryptoData]: A list of candlestick data within the specified date range.
     */
    get: operations["get_candlestick_data_candlestick_data_get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** CryptoData */
    CryptoData: {
      /** Open Time */
      OPEN_TIME?: string | null;
      /** Open */
      OPEN?: number | null;
      /** High */
      HIGH?: number | null;
      /** Low */
      LOW?: number | null;
      /** Close */
      CLOSE?: number | null;
      /** Volume */
      VOLUME?: number | null;
      /** Qav */
      QAV?: number | null;
      /** Num Trades */
      NUM_TRADES?: number | null;
      /** Tbbav */
      TBBAV?: number | null;
      /** Tbqav */
      TBQAV?: number | null;
      /** Ignore */
      IGNORE?: number | null;
      /** Ticker */
      TICKER?: string | null;
      /** Close Time */
      CLOSE_TIME?: string | null;
      /** Close N Days Ago */
      CLOSE_N_DAYS_AGO?: number | null;
      /** Price Change */
      PRICE_CHANGE?: number | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Get Occurrences
   * @description Gets all occurrences in a single dataset where the price change between start_date and end_date is equal to or greater than the specified percentage.
   *
   * Args:
   *     key (str): The dataset key, e.g (ETHUSDT).
   *     percentage_change (float): The percentage change to look for.
   *     start_date (str): The start date of the date range in 'YYYY-MM-DD' format.
   *     end_date (str): The end date of the date range in 'YYYY-MM-DD' format.
   *
   * Returns:
   *     List[CryptoData]: A list of occurrences that match the criteria.
   */
  get_occurrences_occurrences_get: {
    parameters: {
      query: {
        key: string;
        percentage_change: number;
        start_date: string;
        end_date: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CryptoData"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Occurrences For Keys
   * @description Gets all occurrences where the price change between start_date and end_date is equal to or greater than the specified percentage
   * within the given date range for multiple datasets.
   *
   * Args:
   *     keys (List[str]): The S3 keys for the Parquet files.
   *     percentage_change (float): The percentage change to look for.
   *     start_date (str): The start date of the date range in 'YYYY-MM-DD' format.
   *     end_date (str): The end date of the date range in 'YYYY-MM-DD' format.
   *
   * Returns:
   *     List[CryptoData]: A list of occurrences that match the criteria.
   */
  get_occurrences_for_keys_occurrences_keys_get: {
    parameters: {
      query: {
        keys: string[];
        percentage_change: number;
        start_date: string;
        end_date: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CryptoData"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Occurrences For Keys For N Days
   * @description Gets all occurrences where the price change between start_date and end_date is equal to or greater than the specified percentage
   * within the given date range for multiple datasets.
   *
   * Args:
   *     keys (List[str]): The S3 keys for the Parquet files.
   *     percentage_change (float): The percentage change to look for.
   *     start_date (str): The start date of the date range in 'YYYY-MM-DD' format.
   *     end_date (str): The end date of the date range in 'YYYY-MM-DD' format.
   *     day_shift (str): The number of days over which to consider the price_change.
   *
   * Returns:
   *     List[CryptoData]: A list of occurrences that match the criteria.
   */
  get_occurrences_for_keys_for_n_days_occurrences_keys_for_n_days_get: {
    parameters: {
      query: {
        keys: string[];
        percentage_change: number;
        start_date: string;
        end_date: string;
        day_shift: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CryptoData"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Occurrences All
   * @description Gets all occurrences where the price drop between start_date and end_date is equal to or greater than the specified percentage
   * across all datasets.
   *
   * Args:
   *     percentage_change (float): The percentage drop to look for.
   *     start_date (str): The start date of the date range in 'YYYY-MM-DD' format.
   *     end_date (str): The end date of the date range in 'YYYY-MM-DD' format.
   *
   * Returns:
   *     List[CryptoData]: A list of occurrences that match the criteria.
   */
  get_occurrences_all_all_occurrences_get: {
    parameters: {
      query: {
        percentage_change: number;
        start_date: string;
        end_date: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CryptoData"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Datasets
   * @description Lists all available datasets in the S3 bucket.
   *
   * Returns:
   *     List[str]: A list of available dataset keys.
   */
  list_datasets_datasets_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": string[];
        };
      };
    };
  };
  /**
   * List Dataset Dates
   * @description Lists all available dates for a given dataset.
   *
   * Args:
   *     key (str): The S3 key for the dataset.
   *
   * Returns:
   *     List[str]: A list of available dates for the given dataset.
   */
  list_dataset_dates_dataset_dates__key__get: {
    parameters: {
      path: {
        /** @description The key of the dataset */
        key: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": string[];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Candlestick Data
   * @description Gets the candlestick data for a given dataset within a specified date range.
   *
   * Args:
   *     key (str): The dataset key, e.g (ETHUSDT).
   *     start_date (str): The start date of the date range in 'YYYY-MM-DD' format.
   *     end_date (str): The end date of the date range in 'YYYY-MM-DD' format.
   *
   * Returns:
   *     List[CryptoData]: A list of candlestick data within the specified date range.
   */
  get_candlestick_data_candlestick_data_get: {
    parameters: {
      query: {
        /** @description The dataset key, e.g (ETHUSDT) */
        key: string;
        /** @description The start date of the date range in 'YYYY-MM-DD' format */
        start_date: string;
        /** @description The end date of the date range in 'YYYY-MM-DD' format */
        end_date: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CryptoData"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
